NineChronicles.Snapshot.csproj
=> bump: Libplanet and Libplanet.RocksDBStore

NineChronicles.Snapshot.csproj
This bump matches [libplanet-explorer](https://github.com/planetarium/libplanet-explorer/commit/217b5798f68188cd646b70f2c53f311083ed3992).
=> bump libplanet and libplanet.rocksdbstore

NineChronicles.Snapshot.csproj
Reference: https://github.com/planetarium/libplanet/runs/1915972077?check_suite_focus=true#step:13:9
=> bump libplanet

download-snapshot.ps1
=> add: download snapshot script

NineChronicles.Snapshot.csproj, Program.cs
This PR adds removal logic for the unnecessary column families. (see also https://github.com/planetarium/libplanet/pull/1287)
=> Add column family pruning

Program.cs
This PR restores ColumnFamily pruning feature to keep cf usage efficient.
The problem this version had with #29 was that if there was a chain that was longer than the original chain, the pruning process merged it into the original chain and unintentionally appended a longer index. In the case of RocksDBStore , there is metadata (`"p"`) indicating which indexes in the old chain are valid up to and controls this, but since snapshots can't use them directly, I implemented it on here.
Also fixed some performance improvements by fixing TxNonce copy to use RocksDBStore.ForkTxNonces() .
=> Restore CF pruning

Program.cs
This PR creates a full snapshot similar to the `monorocksdb` snapshot so that it is easier to download in a single file.
=> create a full snapshot

NineChronicles.Snapshot.csproj
=> bump libplanet to 0.20.0

NineChronicles.Snapshot.csproj
It probably fixes <https://github.com/planetarium/NineChronicles.Snapshot/issues/78>.
See also <https://github.com/planetarium/libplanet/pull/1654>.
=> Upgrade Libplanet to 0.23.1

NineChronicles.Snapshot.csproj
=> bump libplanet to 0.26.0

NineChronicles.Snapshot.csproj
=> update libplanet to 0.27.0

.github/workflows/build.yml
=> Introduce GitHub Actions build check workflow

NineChronicles.Snapshot.csproj
=> bump libplanet to 0.27.2

Program.cs
Adds code for DB migration, and bumps Libplanet to `0.29.0-dev.20220310084309` which should be fixed after Libplanet release.
=> Bump libplanet and add db migration

NineChronicles.Snapshot.csproj
=> bump libplanet to 0.36.1

NineChronicles.Snapshot.csproj
=> Bump libplanet to 37.0

Program.cs
Resolves https://github.com/planetarium/NineChronicles.Snapshot/issues/157.
=> preserve txexec dir

NineChronicles.Snapshot.csproj, Program.cs
=> bump libplanet to 0.40

download-snapshot.ps1
This pull request just updates `download-snapshot.ps1` script to latest.
=> Update `download-snapshot.ps1` script

Program.cs
I noticed from last release(`v100310`) that the HttpClient PostAsync()(https://github.com/planetarium/NineChronicles.Snapshot/blob/main/Program.cs#L51) doesn't work and the program exits abruptly. I think it's a Slack API hook compatibility issue so I'm reverting the changes and look into using a slack api package instead. PTAL 🙏
=> revert httpclient

NineChronicles.Snapshot/Program.cs
- Combined `txEpochLimit` and `blockEpochLimit` into a single `epochLimit` so that the partitioning files are created consistently (especially tx epoch files).
- Removed the `slackbot-url` since sending these messages to slack is no longer necessary.
- Cleaned up unused methods.
- This version has been tested on the `9c-internal` cluster.
**Note)** The [--slackbot-url](https://github.com/planetarium/9c-k8s-config/blob/main/9c-internal/configmap-snapshot-script.yaml#L308) option should be removed in the `k8s-config` when this PR is merged.
=> combine-block-tx-epochlimit

NineChronicles.Snapshot/Program.cs
=> fix: copy latest 5 stateRootHash

NineChronicles.Snapshot/Program.cs
=> log tip index

.github/workflows/push_docker_image.yml
=> add repo name

NineChronicles.Snapshot/Program.cs
=> check commit of the snapshot tip

NineChronicles.Snapshot/Program.cs
The previous version left out the snapshot tip's block commit when forking to the new chainId and this prevented the validators from mining the next block after the snapshot tip. This PR will preserve the block commit of the snapshot tip.
=> add block commit to the snapshot tip

NineChronicles.Snapshot/Program.cs
=> fix blockcommit related error

NineChronicles.Snapshot/NineChronicles.Snapshot.csproj, NineChronicles.Snapshot/Program.cs, NineChronicles.Snapshot/appsettings.json
SSIA
```
[16:51:52 DBG] Create Snapshot-Partition start.
[16:51:52 ERR] Sequence contains no elements
[16:51:52 ERR] Sequence contains no elements
[16:51:52 ERR] Sequence contains no elements
[16:51:53 DBG] Migration not required.
[16:51:56 DBG] Original Store Tip: #6510099
1. LastCommit: {"block_hash":"c24606ca6892a18a0b6ab5a082c8cc71dfb2748bbbbe196fd10484990d527dae","height":6510098,"round":0,"votes":[{"validator_public_key":"021ebc027706c9b7fdb03bc212657241197c4f7d4f122cbb66f347bee3bfd39551","fla
g":2,"timestamp":"04/13/2023 22:32:15 \u002B00:00"},{"validator_public_key":"0260972c353ba9b1e630d7b488ef0e9250a86286fbc8541e1bcca82f1a50cf8012","flag":2,"timestamp":"04/13/2023 22:32:15 \u002B00:00"},{"validator_public_key":"029
a46496641787a06db32d83dfea3b50ebb681fae9bbf4e60b41ee91d4024965b", …
```
=> Enable logging

NineChronicles.Snapshot/Program.cs
=> log stacktrace

NineChronicles.Snapshot/Program.cs
=> fix run error

.github/workflows/push_docker_image.yml
🔀 Should be backwards compatible with 3.x based version. 😗
=> 🔀 Merge libplanet 4.0 into main

NineChronicles.Snapshot/Program.cs
Since Ctor of BlockChain use AEV from Sloth, removed creation of BlockChain.
=> Bump sloth

Dockerfile, Dockerfile.amd64, Dockerfile.arm64v8
=> Fix libplanet build errors with docker builds

.github/workflows/push_docker_image.yml, Dockerfile, Dockerfile.amd64, Dockerfile.arm64v8, NineChronicles.Snapshot.sln, NineChronicles.Snapshot/NineChronicles.Snapshot.csproj
=> Merge build error fixed version
